name: JDLeonard.net
mail: jd@jdleonard.net
uuid: f9fec136-cbe9-4fdf-af85-c245e165bb7a
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
