name: CI (except master)

on:
  push:
    branches-ignore:
      - 'master'

env:
  # Used by shivammathur/setup-php (as well as our composer commands)
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  php_version: '7.4'
  pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
  pantheon_repo: ${{ secrets.PANTHEON_REPO }}
  pantheon_site_name: ${{ secrets.PANTHEON_SITE_NAME }}

jobs:
  phpcs-drupal:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: guix77/phpcs-drupal-action@v1.0.0

  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: $php_version

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Avoid GitHub rate limit for Composer
        run: composer config -g github-oauth.github.com $COMPOSER_TOKEN

      - name: Composer install
        run: composer install --no-dev --no-interaction --no-progress
