name: Deploy to Pantheon
on:
  push:
    branches:
      - 'gh-actions-2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Installing Terminus
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        run: |
          curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
          terminus auth:login --machine-token=$pantheon-machine-token
      - name: deployer
        env:
          pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        run: |
          git remote add pantheon $pantheon_repo
          git push --force pantheon HEAD:master
          commit_message=$(git log -1 --pretty=%B)
          terminus env:deploy $pantheon_site_name.test --note="Automated deploy: $commit_message"
